# this file is only included on $TARGET_OS="netbsd"
target_bootstrap_chroot() {
    needvar TARGET_OS TARGET_RELEASE TARGET_ARCH TARGET_SETS

    echo "bootstrapping NetBSD"
    [ "$HOST_OS_TYPE" == "netbsd" ] || die "NetBSD jails are only supported on NetBSD hosts"

    local chroot_dir="$(get_builder_chroot_dir)"
    local tarball_dir="$(get_builder_tarball_dir)/netbsd/${TARGET_RELEASE}/${TARGET_ARCH}"
    local tarball_mirror="https://cdn.netbsd.org/pub/NetBSD/NetBSD-${TARGET_RELEASE}/${TARGET_ARCH}/binary/sets"
    local sandbox_name="$(get_builder_chroot_name)"
    local pkgsrc_mirror="https://ftp.netbsd.org/pub/pkgsrc/packages/NetBSD/${TARGET_ARCH}/${TARGET_RELEASE}/All/"
    local release_sets=""

    mkdir -p "$tarball_dir/binary/sets"
    for i in ${TARGET_SETS}; do
        host_fetch_tarball "$tarball_mirror/$i.tar.xz" "$tarball_dir/binary/sets/$i.tar.xz"
        release_sets="$release_sets $i.tar.xz"
    done

    # FIXME: put this into jalirun register
    mkdir -p /usr/pkg/etc/sandboxctl
    sudo tee "/usr/pkg/etc/sandboxctl//$sandbox_name.conf" >/dev/null << __EOF__
## generated by xorg-testing ground - DO NOT EDIT
SANDBOX_TYPE=netbsd-release
SANDBOX_ROOT="$chroot_dir"

NETBSD_RELEASE_RELEASEDIR="${tarball_dir}"
NETBSD_RELEASE_SETS="${release_sets}"
__EOF__

    log "now creating sandbox ..."
    sandboxctl -c "${sandbox_name}" create

    log "deploy ca-certificates"
    if [ -f /etc/resolv.conf ]; then cp /etc/resolv.conf "$chroot_dir/etc/" ; fi
    mkdir -p $chroot_dir/etc/openssl/certs
    cp /etc/openssl/certs/* $chroot_dir/etc/openssl/certs

    sudo sandboxctl -c "${sandbox_name}" run tee /etc/pkg_install.conf >/dev/null << __EOF__
PKG_PATH=${pkgsrc_mirror}
__EOF__

    log "installing pkgin in sandbox ${sandbox_name}"
    sudo sandboxctl -c "${sandbox_name}" run pkg_add pkgin
    sudo sandboxctl -c "${sandbox_name}" run pkgin -y install python312
    sudo sandboxctl -c "${sandbox_name}" run ln -s /usr/pkg/bin/python3.11 /usr/pkg/bin/python3

    log "finished bootstrapping ${sandbox_name}"
}
